__author__ = 'Amber Biology'

from amber_biotools import AntibodyChain
from biotite.sequence import ProteinSequence
import biotite.sequence.align as bioalign
from biotite.sequence.io.fasta import FastaFile
import os, pickle

default_subsitution_matrix = bioalign.SubstitutionMatrix.std_protein_matrix()
scan_locus = {AntibodyChain.LIGHT:['light_chain_kappa', 'light_chain_lambda'], AntibodyChain.HEAVY:['heavy_chain']}
add_regions = {AntibodyChain.HEAVY:{'heavy_chain':'heavy_chain_J'}, AntibodyChain.LIGHT:{'light_chain_kappa':'light_chain_kappa_J', 'light_chain_lambda':'light_chain_lambda_J'}}


human_ab_germ_line =  {

    AntibodyChain.HEAVY: {

    'heavy_chain': {

    'IGHV1-2':      ['QVQLVQSGA','EVKKPGASVKVSCKAS','GYTFTGYY',  'MHWVRQAPGQGLEWMGR','INPNSGGT',  'NYAQKFQ','RVTSTRDTSISTAYMELSRLRSDDTVVYYC', 'AR'],
    'IGHV1-3':      ['QVQLVQSGA','EVKKPGASVKVSCKAS','GYTFTSYA',  'MHWVRQAPGQRLEWMGW','INAGNGNT',  'KYSQKFQ','RVTITRDTSASTAYMELSSLRSEDTAVYYC', 'AR'],
    'IGHV1-8':      ['QVQLVQSGA','EVKKPGASVKVSCKAS','GYTFTSYD',  'INWVRQATGQGLEWMGW','MNPNSGNT',  'GYAQKFQ','RVTMTRNTSISTAYMELSSLRSEDTAVYYC', 'AR'],
    'IGHV1-18':     ['QVQLVQSGA','EVKKPGASVKVSCKAS','GYTFTSYG',  'ISWVRQAPGQGLEWMGW','ISAYNGNT',  'NYAQKLQ','RVTMTTDTSTSTAYMELRSLRSDDTAVYYC', 'AR'],
    'IGHV1-24':     ['QVQLVQSGA','EVKKPGASVKVSCKVS','GYTLTELS',  'MHWVRQAPGKGLEWMGG','FDPEDGET',  'IYAQKFQ','RVTMTEDTSTDTAYMELSSLRSEDTAVYYC', 'AT'],
    'IGHV1-45':     ['QMQLVQSGA','EVKKTGSSVKVSCKAS','GYTFTYRY',  'LHWVRQAPGQALEWMGW','ITPFNGNT',  'NYAQKFQ','DRVTITRDRSMSTAYMELSSLRSEDTAMYYC','AR'],
    'IGHV1-46':     ['QVQLVQSGA','EVKKPGASVKVSCKAS','GYTFTSYY',  'MHWVRQAPGQGLEWMGI','INPSGGST',  'SYAQKFQ','RVTMTRDTSTSTVYMELSSLRSEDTAVYYC', 'AR'],
    'IGHV1-58':     ['QMQLVQSGP','EVKKPGTSVKVSCKAS','GFTFTSSA',  'VQWVRQARGQRLEWIGW','IVVGSGNT',  'NYAQKFQ','ERVTITRDMSTSTAYMELSSLRSEDTAVYYC','AA'],
    'IGHV1-69':     ['QVQLVQSGA','EVKKPGSSVKVSCKAS','GGTFSSYA',  'ISWVRQAPGQGLEWMGG','IIPIFGTA',  'NYAQKFQ','RVTITADESTSTAYMELSSLRSEDTAVYYC', 'AR'],
    'IGHV1-c':                     ['KSGASVKVSCSFS','GFTITSYG',  'IHWVQQSPGQGLEWMGW','INPGNGSP',  'SYAKKFQ','RFTMTRDMSTTTAYTDLSSLTSEDMAVYYY', 'AR'],
    'IGHV1-f':      ['EVQLVQSGA','EVKKPGATVKISCKVS','GYTFTDYY',  'MHWVQQAPGKGLEWMGL','VDPEDGET',  'IYAEKFQ','RVTITADTSTDTAYMELSSLRSEDTAVYYC', 'AT'],
    'IGHV2-5':      ['QITLKESGP','TLVKPTQTLTLTCTFS','GFSLSTSGVG','VGWIRQPPGKALEWLAL','IYWNDDK',  'RYSPSLK','SRLTITKDTSKNQVVLTMTNMDPVDTATYYC','AHR'],
    'IGHV2-26':     ['QVTLKESGP','VLVKPTETLTLTCTVS','GFSLSNARMG','VSWIRQPPGKALEWLAH','IFSNDEK',  'SYSTSLK','SRLTISKDTSKSQVVLTMTNMDPVDTATYYC','ARI'],
    'IGHV2-70':     ['QVTLRESGP','ALVKPTQTLTLTCTFS','GFSLSTSGMC','VSWIRQPPGKALEWLAL','IDWDDDK',  'YYSTSLK','TRLTISKDTSKNQVVLTMTNMDPVDTATYYC','ARI'],
    'IGHV3-7':      ['EVQLVESGG','GLVQPGGSLRLSCAAS','GFTFSSYW',  'MSWVRQAPGKGLEWVAN','IKQDGSEK',  'YYVDSVK','RFTISRDNAKNSLYLQMNSLRAEDTAVYYC', 'AR'],
    'IGHV3-9':      ['EVQLVESGG','GLVQPGRSLRLSCAAS','GFTFDDYA',  'MHWVRQAPGKGLEWVSG','ISWNSGSI',  'GYADSVK','RFTISRDNAKNSLYLQMNSLRAEDTALYYC', 'AKD'],
    'IGHV3-11':     ['QVQLVESGG','GLVKPGGSLRLSCAAS','GFTFSDYY',  'MSWIRQAPGKGLEWVSY','ISSSGSTI',  'YYADSVK','RFTISRDNAKNSLYLQMNSLRAEDTAVYYC', 'AR'],
    'IGHV3-13':     ['EVQLVESGG','GLVQPGGSLRLSCAAS','GFTFSSYD',  'MHWVRQATGKGLEWVSA','IGTAGDT',   'YYPGSVK','RFTISRENAKNSLYLQMNSLRAGDTAVYYC', 'AR'],
    'IGHV3-15':     ['EVQLVESGG','GLVKPGGSLRLSCAAS','GFTFSNAW',  'MSWVRQAPGKGLEWVGR','IKSKTDGGTT','DYAAPVK','RFTISRDDSKNTLYLQMNSLKTEDTAVYYC', 'TT'],
    'IGHV3-16':     ['EVQLVESGG','GLVQPGGSLRLSCAAS','GFTFSNSD',  'MNWARKAPGKGLEWVSG','VSWNGSRT',  'HYVDSVK','RRFIISRDNSRNSLYLQKNRRRAEDMAVYYC','VR'],
    'IGHV3-19':     ['TVQLVESGG','GLVEPGGSLRLSCAAS','GFTFSNSD',  'MNWVRQAPGKGLEWVSG','VSWNGSRT',  'HYADSVK','RFIISRDNSRNFLYQQMNSLRPEDMAVYYC', 'VR'],
    'IGHV3-20':     ['EVQLVESGG','GVVRPGGSLRLSCAAS','GFTFDDYG',  'MSWVRQAPGKGLEWVSG','INWNGGST',  'GYADSVK','RFTISRDNAKNSLYLQMNSLRAEDTALYHC', 'AR'],
    'IGHV3-21':     ['EVQLVESGG','GLVKPGGSLRLSCAAS','GFTFSSYS',  'MNWVRQAPGKGLEWVS', 'ISSSSSYI',  'YYADSVK','RFTISRDNAKNSLYLQMNSLRAEDTAVYYC', 'AR'],
    'IGHV3-23':     ['EVQLLESGG','GLVQPGGSLRLSCAAS','GFTFSSYA',  'MSWVRQAPGKGLEWVSA','ISGSGGST',  'YYADSVK','RFTISRDNSKNTLYLQMNSLRAEDTAVYYC', 'AK'],
    'IGHV3-30':     ['QVQLVESGG','GVVQPGRSLRLSCAAS','GFTFSSYA',  'MHWVRQAPGKGLEWVAV','ISYDGSNK',  'YYADSVK','RFTISRDNSKNTLYLQMNSLRAEDTAVYYC', 'AR'],
    'IGHV3-30-3':   ['QVQLVESGG','GVVQPGRSLRLSCAAS','GFTFSSYA',  'MHWVRQAPGKGLEWVAV','ISYDGSNK',  'YYADSVK','RFTISRDNSKNTLYLQMNSLRAEDTAVYYC', 'AR'],
    'IGHV3-33':     ['QVQLVESGG','GVVQPGRSLRLSCAAS','GFTFSSYG',  'MHWVRQAPGKGLEWVAV','IWYDGSNK',  'YYADSVK','RFTISRDNSKNTLYLQMNSLRAEDTAVYYC', 'AR'],
    'IGHV3-35':     ['EVQLVESGG','GLVQPGGSLRLSCAAS','GFTFSNSD',  'MNWVHQAPGKGLEWVSG','VSWNGSRT',  'HYADSVK','RFIISRDNSRNTLYLQTNSLRAEDTAVYYC', 'VR'],
    'IGHV3-38':     ['EVQLVESGG','GLVQPRGSLRLSCAAS','GFTVSSNE',  'MSWIRQAPGKGLEWVSS','ISGGST',    'YYADSRK','RFTISRDNSKNTLYLQMNNLRAEGTAAYYC', 'ARY'],
    'IGHV3-43':     ['EVQLVESGG','VVVQPGGSLRLSCAAS','GFTFDDYT',  'MHWVRQAPGKGLEWVSL','ISWDGGST',  'YYADSVK','RFTISRDNSKNSLYLQMNSLRTEDTALYYC', 'AKD'],
    'IGHV3-47':     ['EDQLVESGG','GLVQPGGSLRPSCAAS','GFAFSSYA',  'LHWVRRAPGKGLEWVSA','IGTGGDT',  'YYADSVM','RFTISRDNAKKSLYLHMNSLIAEDMAVYYC', 'AR'],
    'IGHV3-48':     ['EVQLVESGG','GLVQPGGSLRLSCAAS','GFTFSSYS',  'MNWVRQAPGKGLEWVSY','ISSSSSTI',  'YYADSVK','RFTISRDNAKNSLYLQMNSLRAEDTAVYYC', 'AR'],
    'IGHV3-49':     ['EVQLVESGG','GLVQPGRSLRLSCTAS','GFTFGDYA',  'MSWFRQAPGKGLEWVGF','IRSKAYGGTT','EYTASVK','RFTISRDGSKSIAYLQMNSLKTEDTAVYYC', 'TR'],
    'IGHV3-53':     ['EVQLVESGG','GLIQPGGSLRLSCAAS','GFTVSSNY',  'MSWVRQAPGKGLEWVSV','IYSGGST',  'YYADSVK','RFTISRDNSKNTLYLQMNSLRAEDTAVYYC', 'AR'],
    'IGHV3-64':     ['EVQLVESGG','GLVQPGGSLRLSCAAS','GFTFSSYA',  'MHWVRQAPGKGLEYVSA','ISSNGGST',  'YYANSVK','RFTISRDNSKNTLYLQMGSLRAEDMAVYYC', 'AR'],
    'IGHV3-66':     ['EVQLVESGG','GLVQPGGSLRLSCAAS','GFTVSSNY',  'MSWVRQAPGKGLEWVSV','IYSGGST',  'YYADSVK','RFTISRDNSKNTLYLQMNSLRAEDTAVYYC', 'AR'],
    'IGHV3-72':     ['EVQLVESGG','GLVQPGGSLRLSCAAS','GFTFSDHY',  'MDWVRQAPGKGLEWVGR','TRNKANSYTT','EYAASVK','RFTISRDDSKNSLYLQMNSLKTEDTAVYYC', 'AR'],
    'IGHV3-73':     ['EVQLVESGG','GLVQPGGSLKLSCAAS','GFTFSGSA',  'MHWVRQASGKGLEWVGR','IRSKANSYAT','AYAASVK','RFTISRDDSKNTAYLQMNSLKTEDTAVYYC', 'TR'],
    'IGHV3-74':     ['EVQLVESGG','GLVQPGGSLRLSCAAS','GFTFSSYW',  'MHWVRQAPGKGLVWVSR','INSDGSST',  'SYADSVK','RFTISRDNAKNTLYLQMNSLRAEDTAVYYC', 'AR'],
    'IGHV3-d':      ['EVQLVESRG','VLVQPGGSLRLSCAAS','GFTVSSNE',  'MSWVRQAPGKGLEWVSS','ISGGST',    'YYADSRK','RFTISRDNSKNTLHLQMNSLRAEDTAVYYC', 'KK'],
    'IGHV3-h':      ['EVQLVESGG','GLVKPGGSLRLSCAAS','GFTFSDYY',  'MNWVRQAPGKGLEWVSS','ISSSSTI',  'YYADSVK','RFTISRDNAKNSLYLQMNSLRAEDTAVYYC', 'AR'],
    'IGHV4-4':      ['QVQLQESGP','GLVKPPGTLSLTCAVS','GGSISSSNW','WSWVRQPPGKGLEWIGE','IYHSGST',  'NYNPSLK','RVTISVDKSKNQFSLKLSSVTAADTAVYCC', 'AR'],
    'IGHV4-28':     ['QVQLQESGP','GLVKPSDTLSLTCAVS','GYSISSSNW','WGWIRQPPGKGLEWIGY','IYYSGST',  'YYNPSLK','RVTMSVDTSKNQFSLKLSSVTAVDTAVYYC', 'AR'],
    'IGHV4-30-2':   ['QLQLQESGS','GLVKPSQTLSLTCAVS','GGSISSGGYS','WSWIRQPPGKGLEWIGY','IYHSGST',  'YYNPSLK','RVTISVDRSKNQFSLKLSSVTAADTAVYYC', 'AR'],
    'IGHV4-30-4':   ['QVQLQESGP','GLVKPSQTLSLTCTVS','GGSISSGDYY','WSWIRQPPGKGLEWIGY','IYYSGST',  'YYNPSLK','RVTISVDTSKNQFSLKLSSVTAADTAVYYC', 'AR'],
    'IGHV4-31':     ['QVQLQESGP','GLVKPSQTLSLTCTVS','GGSISSGGYY','WSWIRQHPGKGLEWIGY','IYYSGST',  'YYNPSLK','LVTISVDTSKNQFSLKLSSVTAADTAVYYC', 'AR'],
    'IGHV4-34':     ['QVQLQQWGA','GLLKPSETLSLTCAVY','GGSFSGYY',  'WSWIRQPPGKGLEWIGE','INHSGST',  'NYNPSLK','RVTISVDTSKNQFSLKLSSVTAADTAVYYC', 'AR'],
    'IGHV4-39':     ['QLQLQESGP','GLVKPSETLSLTCTVS','GGSISSSSYY','WGWIRQPPGKGLEWIGS','IYYSGST',  'YYNPSLK','RVTISVDTSKNQFSLKLSSVTAADTAVYYC', 'AR'],
    'IGHV4-55':     ['QVQLQESGP','GLVKPSETLSLICAVS','GDSISSGNW','*IWVRQPPGKGLEWIGE','IHHSGST',  'YYNPSLK','RITMSVDTSKNQFYLKLSSVTAADTAVYYC', 'AR'],
    'IGHV4-59':     ['QVQLQESGP','GLVKPSETLSLTCTVS','GGSISSYY',  'WSWIRQPPGKGLEWIGY','IYYSGST',  'NYNPSLK','RVTISVDTSKNQFSLKLSSVTAADTAVYYC', 'AR'],
    'IGHV4-61':     ['QVQLQESGP','GLVKPSETLSLTCTVS','GGSVSSGSYY','WSWIRQPPGKGLEWIGY','IYYSGST',  'NYNPSLK','RVTISVDTSKNQFSLKLSSVTAADTAVYYC', 'AR'],
    'IGHV4-b':      ['QVQLQESGP','GLVKPSETLSLTCAVS','GYSISSGYY','WGWIRQPPGKGLEWIGS','IYHSGST',  'YYNPSLK','RVTISVDTSKNQFSLKLSSVTAADTAVYYC', 'AR'],
    'IGHV5-51':     ['EVQLVQSGA','EVKKPGESLKISCKGS','GYSFTSYW',  'IGWVRQMPGKGLEWMGI','IYPGDSDT',  'RYSPSFQ','QVTISADKSISTAYLQWSSLKASDTAMYYC', 'AR'],
    'IGHV5-a':      ['EVQLVQSGA','EVKKPGESLRISCKGS','GYSFTSYW',  'ISWVRQMPGKGLEWMGR','IDPSDSYT',  'NYSPSFQ','HVTISADKSISTAYLQWSSLKASDTAMYYC', 'AR'],
    'IGHV6-1':      ['QVQLQQSGP','GLVKPSQTLSLTCAIS','GDSVSSNSAA','WNWIRQSPSRGLEWLGR','TYYRSKWYN', 'DYAVSVK','RITINPDTSKNQFSLQLNSVTPEDTAVYYC', 'AR'],
    'IGHV7-4-1':    ['QVQLVQSGS','ELKKPGASVKVSCKAS','GYTFTSYA',  'MNWVRQAPGQGLEWMGW','INTNTGNP',  'TYAQGFT','RFVFSLDTSVSTAYLQICSLKAEDTAVYYC', 'AR'],
    'IGHV7-81':     ['QVQLVQSGH','EVKQPGASVKVSCKAS','GYSFTTYG',  'MNWVPQAPGQGLEWMGW','FNTYTGNP',  'TYAQGFT','RFVFSMDTSASTAYLQISSLKAEDMAMYYC', 'AR']},

    'heavy_chain_J':{
    'IGHJ1':'AEYFQHWGQGTLVTVSS',
    'IGHJ2':'YWYFDLWGRGTLVTVSS',
    'IGHJ3':'AFDVWGQGTMVTVSS',
    'IGHJ4':'YFDYWGQGTLVTVSS',
    'IGHJ5':'NWFDSWGQGTLVTVSS',
    'IGHJ6':'YYYYYGMDVWGQGTTVTVSS'}},

    AntibodyChain.LIGHT: {

    'light_chain_kappa': {

    'IGKV1-5':[       'DIQMTQSPSTLSASVGDRVTITCRAS','QSISSW',       'LAWYQQKPGKAPKLLIY','DAS','SLESGVP','SRFSGSG','SGTEFTLTISSLQPDDFATYYC','QQYNSYS'],
    'IGKV1-6':[       'AIQMTQSPSSLSASVGDRVTITCRAS','QGIRND',       'LGWYQQKPGKAPKLLIY','AAS','SLQSGVP','SRFSGSG','SGTDFTLTISSLQPEDFATYYC','LQDYNYP'],
    'IGKV1-8':[       'AIRMTQSPSSFSASTGDRVTITCRAS','QGISSY',       'LAWYQQKPGKAPKLLIY','AAS','TLQSGVP','SRFSGSG','SGTDFTLTISCLQSEDFATYYC','QQYYSYP'],
    'IGKV1D-8':[      'VIWMTQSPSLLSASTGDRVTISCRMS','QGISSY',       'LAWYQQKPGKAPELLIY','AAS','TLQSGVP','SRFSGSG','SGTDFTLTISCLQSEDFATYYC','QQYYSFP'],
    'IGKV1-9':[       'DIQLTQSPSFLSASVGDRVTITCRAS','QGISSY',       'LAWYQQKPGKAPKLLIY','AAS','TLQSGVP','SRFSGSG','SGTEFTLTISSLQPEDFATYYC','QQLNSYP'],
    'IGKV1-12':[      'DIQMTQSPSSVSASVGDRVTITCRAS','QGISSW',       'LAWYQQKPGKAPKLLIY','AAS','SLQSGVP','SRFSGSG','SGTDFTLTISSLQPEDFATYYC','QQANSFP'],
    'IGKV1D-12':[     'DIQMTQSPSSVSASVGDRVTITCRAS','QGISSW',       'LAWYQQKPGKAPKLLIY','AAS','SLQSGVP','SRFSGSG','SGTDFTLTISSLQPEDFATYYC','QQANSFP'],
    'IGKV1-13*02':[   'AIQLTQSPSSLSASVGDRVTITCRAS','QGISSA',       'LAWYQQKPGKAPKLLIY','DAS','SLESGVP','SRFSGSG','SGTDFTLTISSLQPEDFATYYC','QQFNSYP'],
    'IGKV1D-13':[     'AIQLTQSPSSLSASVGDRVTITCRAS','QGISSA',       'LAWYQQKPGKAPKLLIY','DAS','SLESGVP','SRFSGSG','SGTDFTLTISSLQPEDFATYYC','QQFNNYP'],
    'IGKV1-16':[      'DIQMTQSPSSLSASVGDRVTITCRAS','QGISNY',       'LAWFQQKPGKAPKSLIY','AAS','SLQSGVP','SRFSGSG','SGTDFTLTISSLQPEDFATYYC','QQYNSYP'],
    'IGKV1D-16':[     'DIQMTQSPSSLSASVGDRVTITCRAS','QGISSW',       'LAWYQQKPEKAPKSLIY','AAS','SLQSGVP','SRFSGSG','SGTDFTLTISSLQPEDFATYYC','QQYNSYP'],
    'IGKV1-17':[      'DIQMTQSPSSLSASVGDRVTITCRAS','QGIRND',       'LGWYQQKPGKAPKRLIY','AAS','SLQSGVP','SRFSGSG','SGTEFTLTISSLQPEDFATYYC','LQHNSYP'],
    'IGKV1D-17':[     'NIQMTQSPSAMSASVGDRVTITCRAR','QGISNY',       'LAWFQQKPGKVPKHLIY','AAS','SLQSGVP','SRFSGSG','SGTEFTLTISSLQPEDFATYYC','LQHNSYP'],
    'IGKV1-27':[      'DIQMTQSPSSLSASVGDRVTITCRAS','QGISNY',       'LAWYQQKPGKVPKLLIY','AAS','TLQSGVP','SRFSGSG','SGTDFTLTISSLQPEDVATYYC','QKYNSAP'],
    'IGKV1-33':[      'DIQMTQSPSSLSASVGDRVTITCQAS','QDISNY',       'LNWYQQKPGKAPKLLIY','DAS','NLETGVP','SRFSGSG','SGTDFTFTISSLQPEDIATYYC','QQYDNLP'],
    'IGKV1D-33':[     'DIQMTQSPSSLSASVGDRVTITCQAS','QDISNY',       'LNWYQQKPGKAPKLLIY','DAS','NLETGVP','SRFSGSG','SGTDFTFTISSLQPEDIATYYC','QQYDNLP'],
    'IGKV1-37':[      'DIQLTQSPSSLSASVGDRVTITCRVS','QGISSY',       'LNWYRQKPGKVPKLLIY','SAS','NLQSGVP','SRFSGSG','SGTDFTLTISSLQPEDVATYYG','QRTYNAP'],
    'IGKV1D-37':[     'DIQLTQSPSSLSASVGDRVTITCRVS','QGISSY',       'LNWYRQKPGKVPKLLIY','SAS','NLQSGVP','SRFSGSG','SGTDFTLTISSLQPEDVATYYG','QRTYNAP'],
    'IGKV1-39':[      'DIQMTQSPSSLSASVGDRVTITCRAS','QSISSY',       'LNWYQQKPGKAPKLLIY','AAS','SLQSGVP','SRFSGSG','SGTDFTLTISSLQPEDFATYYC','QQSYSTP'],
    'IGKV1D-39':[     'DIQMTQSPSSLSASVGDRVTITCRAS','QSISSY',       'LNWYQQKPGKAPKLLIY','AAS','SLQSGVP','SRFSGSG','SGTDFTLTISSLQPEDFATYYC','QQSYSTP'],
    'IGKV1D-42':[     'DIQMIQSPSFLSASVGDRVSIICWAS','EGISSN',       'LAWYLQKPGKSPKLFLY','DAK','DLHPGVS','SRFSGRG','SGTDFTLTIISLKPEDFAAYYC','KQDFSYP'],
    'IGKV1D-43':[     'AIRMTQSPFSLSASVGDRVTITCWAS','QGISSY',       'LAWYQQKPAKAPKLFIY','YAS','SLQSGVP','SRFSGSG','SGTDYTLTISSLQPEDFATYYC','QQYYSTP'],
    'IGKV2-24':[      'DIVMTQTPLSSPVTLGQPASISCRSS','QSLVHSDGNTY',  'LSWLQQRPGQPPRLLIY','KIS','NRFSGVP','DRFSGSG','AGTDFTLKISRVEAEDVGVYYC','MQATQFP'],
    'IGKV2D-24':[     'DIVMTQTPLSSPVTLGQPASISFRSS','QSLVHSDGNTY',  'LSWLQQRPGQPPRLLIY','KVS','NRFSGVP','DRFSGSG','AGTDFTLKISRVEAEDVGVYYC','TQATQFP'],
    'IGKV2-28':[      'DIVMTQSPLSLPVTPGEPASISCRSS','QSLLHSNGYNY',  'LDWYLQKPGQSPQLLIY','LGS','NRASGVP','DRFSGSG','SGTDFTLKISRVEAEDVGVYYC','MQALQTP'],
    'IGKV2D-28':[     'DIVMTQSPLSLPVTPGEPASISCRSS','QSLLHSNGYNY',  'LDWYLQKPGQSPQLLIY','LGS','NRASGVP','DRFSGSG','SGTDFTLKISRVEAEDVGVYYC','MQALQTP'],
    'IGKV2-29*02':[   'DIVMTQTPLSLSVTPGQPASISCKSS','QSLLHSDGKTY',  'LYWYLQKPGQSPQLLIY','EVS','SRFSGVP','DRFSGSG','SGTDFTLKISRVEAEDVGVYY*','MQGIHLP'],
    'IGKV2D-29':[     'DIVMTQTPLSLSVTPGQPASISCKSS','QSLLHSDGKTY',  'LYWYLQKPGQPPQLLIY','EVS','NRFSGVP','DRFSGSG','SGTDFTLKISRVEAEDVGVYYC','MQSIQLP'],
    'IGKV2-30':[      'DVVMTQSPLSLPVTLGQPASISCRSS','QSLVYSDGNTY',  'LNWFQQRPGQSPRRLIY','KVS','NRDSGVP','DRFSGSG','SGTDFTLKISRVEAEDVGVYYC','MQGTHWP'],
    'IGKV2D-30':[     'DVVMTQSPLSLPVTLGQPASISCRSS','QSLVYSDGNTY',  'LNWFQQRPGQSPRRLIY','KVS','NWDSGVP','DRFSGSG','SGTDFTLKISRVEAEDVGVYYC','MQGTHWP'],
    'IGKV2-40':[      'DIVMTQTPLSLPVTPGEPASISCRSS','QSLLDSDDGNTY', 'LDWYLQKPGQSPQLLIY','TLS','YRASGVP','DRFSGSG','SGTDFTLKISRVEAEDVGVYYC','MQRIEFP'],
    'IGKV2D-40':[     'DIVMTQTPLSLPVTPGEPASISCRSS','QSLLDSDDGNTY', 'LDWYLQKPGQSPQLLIY','TLS','YRASGVP','DRFSGSG','SGTDFTLKISRVEAEDVGVYYC','MQRIEFP'],
    'IGKV3-7':[       'EIVMTQSPPTLSLSPGERVTLSCRAS','QSVSSSY',      'LTWYQQKPGQAPRLLIY','GAS','TRATSIP','ARFSGSG','SGTDFTLTISSLQPEDFAVYYC','QQDHNLP'],
    'IGKV3D-7':[      'EIVMTQSPATLSLSPGERATLSCRAS','QSVSSSY',      'LSWYQQKPGQAPRLLIY','GAS','TRATGIP','ARFSGSG','SGTDFTLTISSLQPEDFAVYYC','QQDYNLP'],
    'IGKV3-11':[      'EIVLTQSPATLSLSPGERATLSCRAS','QSVSSY',       'LAWYQQKPGQAPRLLIY','DAS','NRATGIP','ARFSGSG','SGTDFTLTISSLEPEDFAVYYC','QQRSNWP'],
    'IGKV3D-11':[     'EIVLTQSPATLSLSPGERATLSCRAS','QGVSSY',       'LAWYQQKPGQAPRLLIY','DAS','NRATGIP','ARFSGSG','PGTDFTLTISSLEPEDFAVYYC','QQRSNWH'],
    'IGKV3-15':[      'EIVMTQSPATLSVSPGERATLSCRAS','QSVSSN',       'LAWYQQKPGQAPRLLIY','GAS','TRATGIP','ARFSGSG','SGTEFTLTISSLQSEDFAVYYC','QQYNNWP'],
    'IGKV3D-15':[     'EIVMTQSPATLSVSPGERATLSCRAS','QSVSSN',       'LAWYQQKPGQAPRLLIY','GAS','TRATGIP','ARFSGSG','SGTEFTLTISSLQSEDFAVYYC','QQYNNWP'],
    'IGKV3-20':[      'EIVLTQSPGTLSLSPGERATLSCRAS','QSVSSSY',      'LAWYQQKPGQAPRLLIY','GAS','SRATGIP','DRFSGSG','SGTDFTLTISRLEPEDFAVYYC','QQYGSSP'],
    'IGKV3D-20':[     'EIVLTQSPATLSLSPGERATLSCGAS','QSVSSSY',      'LAWYQQKPGLAPRLLIY','DAS','SRATGIP','DRFSGSG','SGTDFTLTISRLEPEDFAVYYC','QQYGSSP'],
    'IGKV4-1':[       'DIVMTQSPDSLAVSLGERATINCKSS','QSVLYSSNNKNY', 'LAWYQQKPGQPPKLLIY','WAS','TRESGVP','DRFSGSG','SGTDFTLTISSLQAEDVAVYYC','QQYYSTP'],
    'IGKV5-2':[       'ETTLTQSPAFMSATPGDKVNISCKAS','QDIDDD',       'MNWYQQKPGEAAIFIIQ','EAT','TLVPGIP','PRFSGSG','YGTDFTLTINNIESEDAAYYFC','LQHDNFP'],
    'IGKV6-21':[      'EIVLTQSPDFQSVTPKEKVTITCRAS','QSIGSS',       'LHWYQQKPDQSPKLLIK','YAS','QSFSGVP','SRFSGSG','SGTDFTLTINSLEAEDAATYYC','HQSSSLP'],
    'IGKV6D-21':[     'EIVLTQSPDFQSVTPKEKVTITCRAS','QSIGSS',       'LHWYQQKPDQSPKLLIK','YAS','QSFSGVP','SRFSGSG','SGTDFTLTINSLEAEDAATYYC','HQSSSLP'],
    'IGKV6D-41':[     'DVVMTQSPAFLSVTPGEKVTITCQAS','EGIGNY',       'LYWYQQKPDQAPKLLIK','YAS','QSISGVP','SRFSGSG','SGTDFTFTISSLEAEDAATYYC','QQGNKHP'],
    'IGKV7-3':[       'DIVLTQSPASLAVSPGQRATITCRAS','ESVSFLGINL',   'IHWYQQKPGQPPKLLIY','QAS','NKDTGVP','ARFSGSG','SGTDFTLTINPVEANDTANYYC','LQSKNFP']},

    'light_chain_kappa_J':{
    'IGKJ1':'WTFGQGTKVEIK',
    'IGKJ2':'YTFGQGTKLEIK',
    'IGKJ3':'FTFGPGTKVDIK',
    'IGKJ4':'LTFGGGTKVEIK',
    'IGKJ5':'ITFGQGTRLEIK'},

    'light_chain_lambda':{

    'IGLV1-36':[  'QSVLTQPPS','VSEAPRQRVTISCSGS','SSNIGNNA',     'VNWYQQLPGKAPKLLIY','YDD',        'LLPSGVS','DRFSGSK','SGTSASLAISGLQSEDEADYYC','AAWDDSLNG'],
    'IGLV1-40':[  'QSVLTQPPS','VSGAPGQRVTISCTGS','SSNIGAGYD',    'VHWYQQLPGTAPKLLIY','GNS',        'NRPSGVP','DRFSGSK','SGTSASLAITGLQAEDEADYYC','QSYDSSLSG'],
    'IGLV1-41':[  'QSVLTQPPS','VSAAPGQKVTISCSGS','SSDMGNYA',     'VSWYQQLPGTAPKLLIY','ENN',        'KRPSGIP','DRFSGSK','SGTSATLGITGLWPEDEADYYC','LAWDTSPRA'],
    'IGLV1-44':[  'QSVLTQPPS','ASGTPGQRVTISCSGS','SSNIGSNT',     'VNWYQQLPGTAPKLLIY','SNN',        'QRPSGVP','DRFSGSK','SGTSASLAISGLQSEDEADYYC','AAWDDSLNG'],
    'IGLV1-47':[  'QSVLTQPPS','ASGTPGQRVTISCSGS','SSNIGSNY',     'VYWYQQLPGTAPKLLIY','RNN',        'QRPSGVP','DRFSGSK','SGTSASLAISGLRSEDEADYYC','AAWDDSLSG'],
    'IGLV1-50':[  'QSVLTQPPS','VSGAPGQRVTISCTGS','SSNIGAGYV',    'VHWYQQLPGTAPKLLIY','GNS',        'NRPSGVP','DQFSGSK','SGTSASLAITGLQSEDEADYYC','KAWDNSLNA'],
    'IGLV1-51':[  'QSVLTQPPS','VSAAPGQKVTISCSGS','SSNIGNNY',     'VSWYQQLPGTAPKLLIY','DNN',        'KRPSGIP','DRFSGSK','SGTSATLGITGLQTGDEADYYC','GTWDSSLSA'],
    'IGLV2-8':[   'QSALTQPPS','ASGSPGQSVTISCTGT','SSDVGGYNY',    'VSWYQQHPGKAPKLMIY','EVS',        'KRPSGVP','DRFSGSK','SGNTASLTVSGLQAEDEADYYC','SSYAGSNNF'],
    'IGLV2-11':[  'QSALTQPRS','VSGSPGQSVTISCTGT','SSDVGGYNY',    'VSWYQQHPGKAPKLMIY','DVS',        'KRPSGVP','DRFSGSK','SGNTASLTISGLQAEDEADYYC','CSYAGSYTF'],
    'IGLV2-14':[  'QSALTQPAS','VSGSPGQSITISCTGT','SSDVGGYNY',    'VSWYQQHPGKAPKLMIY','EVS',        'NRPSGVS','NRFSGSK','SGNTASLTISGLQAEDEADYYC','SSYTSSSTL'],
    'IGLV2-18':[  'QSALTQPPS','VSGSPGQSVTISCTGT','SSDVGSYNR',    'VSWYQQPPGTAPKLMIY','EVS',        'NRPSGVP','DRFSGSK','SGNTASLTISGLQAEDEADYYC','SLYTSSSTF'],
    'IGLV2-23':[  'QSALTQPAS','VSGSPGQSITISCTGT','SSDVGSYNL',    'VSWYQQHPGKAPKLMIY','EGS',        'KRPSGVS','NRFSGSK','SGNTASLTISGLQAEDEADYYC','CSYAGSSTL'],
    'IGLV2-33':[  'QSALTQPPF','VSGAPGQSVTISCTGT','SSDVGDYDH',    'VFWYQKRLSTTSRLLIY','NVN',        'TRPSGIS','DLFSGS', 'SGNMASLTISGLKSEVEANYHC','SLYSSSYTF'],
    'IGLV3-1':[   'SYELTQPPS','VSVSPGQTASITCSGD','KLGDKY',       'ACWYQQKPGQSPVLVIY','QDS',        'KRPSGIP','ERFSGSN','SGNTATLTISGTQAMDEADYYC','QAWDSSTA'],
    'IGLV3-9':[   'SYELTQPLS','VSVALGQTARITCGGN','NIGSKN',       'VHWYQQKPGQAPVLVIY','RDS',        'NRPSGIP','ERFSGSN','SGNTATLTISRAQAGDEADYYC','QVWDSSTA'],
    'IGLV3-10':[  'SYELTQPPS','VSVSPGQTARITCSGD','ALPKKY',       'AYWYQQKSGQAPVLVIY','EDS',        'KRPSGIP','ERFSGSS','SGTMATLTISGAQVEDEADYYC','YSTDSSGNH'],
    'IGLV3-12':[  'SYELTQPHS','VSVATAQMARITCGGN','NIGSKA',       'VHWYQQKPGQDPVLVIY','SDS',        'NRPSGIP','ERFSGSN','PGNTTTLTISRIEAGDEADYYC','QVWDSSSDH'],
    'IGLV3-16':[  'SYELTQPPS','VSVSLGQMARITCSGE','ALPKKY',       'AYWYQQKPGQFPVLVIY','KDS',        'ERPSGIP','ERFSGSS','SGTIVTLTISGVQAEDEADYYC','LSADSSGTY'],
    'IGLV3-19':[  'SSELTQDPA','VSVALGQTVRITCQGD','SLRSYY',       'ASWYQQKPGQAPVLVIY','GKN',        'NRPSGIP','DRFSGSS','SGNTASLTITGAQAEDEADYYC','NSRDSSGNH'],
    'IGLV3-21':[  'SYVLTQPPS','VSVAPGKTARITCGGN','NIGSKS',       'VHWYQQKPGQAPVLVIY','YDS',        'DRPSGIP','ERFSGSN','SGNTATLTISRVEAGDEADYYC','QVWDSSSDH'],
    'IGLV3-22':[  'SYELTQLPS','VSVSPGQTARITCSGD','VLGENY',       'ADWYQQKPGQAPELVIY','EDS',        'ERYPGIP','ERFSGST','SGNTTTLTISRVLTEDEADYYC','LSGDEDN'],
    'IGLV3-25':[  'SYELMQPPS','VSVSPGQTARITCSGD','ALPKQY',       'AYWYQQKPGQAPVLVIY','KDS',        'ERPSGIP','ERFSGSS','SGTTVTLTISGVQAEDEADYYC','QSADSSGTY'],
    'IGLV3-27':[  'SYELTQPSS','VSVSPGQTARITCSGD','VLAKKY',       'ARWFQQKPGQAPVLVIY','KDS',        'ERPSGIP','ERFSGSS','SGTTVTLTISGAQVEDEADYYC','YSAADNN'],
    'IGLV3-32':[  'SSGPTQVPA','VSVALGQMARITCQGD','SMEGSY',       'EHWYQQKPGQAPVLVIY','DSS',        'DRPSRIP','ERFSGSK','SGNTTTLTITGAQAEDEADYYY','QLIDNHA'],
    'IGLV4-3':[   'LPVLTQPPS','ASALLGASIKLTCTLS','SEHSTYT',      'IEWYQQRPGRSPQYIMK','VKSDGSH',    'SKGDGIP','DRFMGSS','SGADRYLTFSNLQSDDEAEYHC','GESHTIDGQVG*'],
    'IGLV4-60':[  'QPVLTQSSS','ASASLGSSVKLTCTLS','SGHSSYI',      'IAWHQQQPGKAPRYLMK','LEGSGSY',    'NKGSGVP','DRFSGSS','SGADRYLTISNLQLEDEADYYC','ETWDSNT'],
    'IGLV4-69':[  'QLVLTQSPS','ASASLGASVKLTCTLS','SGHSSYA',      'IAWHQQQPEKGPRYLMK','LNSDGSH',    'SKGDGIP','DRFSGSS','SGAERYLTISSLQSEDEADYYC','QTWGTGI'],
    'IGLV5-37':[  'QPVLTQPPS','SSASPGESARLTCTLP','SDINVGSYN',    'IYWYQQKPGSPPRYLLY','YYSDSDK',    'GQGSGVP','SRFSGSKDASANTGILLISGLQSEDEADYYC', 'MIWPSNAS'],
    'IGLV5-39':[  'QPVLTQPTS','LSASPGASARFTCTLR','SGINVGTYR',    'IYWYQQKPGSLPRYLLR','YKSDSDK',    'QQGSGVP','SRFSGSKDASTNAGLLLISGLQSEDEADYYC', 'AIWYSSTS'],
    'IGLV5-45':[  'QAVLTQPAS','LSASPGASASLTCTLR','SGINVGTYR',    'IYWYQQKPGSPPQYLLR','YKSDSDK',    'QQGSGVP','SRFSGSKDASANAGILLISGLQSEDEADYYC', 'MIWHSSAS'],
    'IGLV5-48':[  'QPVLTQPTS','LSASPGASARLTCTLR','SGINLGSYR',    'IFWYQQKPESPPRYLLS','YYSDSSK',    'HQGSGVP','SRFSGSKDASSNAGILVISGLQSEDEADYYC', 'MIWHSSAS'],
    'IGLV5-52':[  'QPVLTQPSS','HSASSGASVRLTCMLS','SGFSVGDFW',    'IRWYQQKPGNPPRYLLY','YHSDSNK',    'GQGSGVP','SRFSGSNDASANAGILRISGLQPEDEADYYC', 'GTWHSNSKT'],
    'IGLV6-57':[  'NFMLTQPHS','VSESPGKTVTISCTRS','SGSIASNY',     'VQWYQQRPGSSPTTVIY','EDN',        'QRPSGVP','DRFSGSIDSSSNSASLTISGLKTEDEADYYC', 'QSYDSSN'],
    'IGLV7-43':[  'QTVVTQEPS','LTVSPGGTVTLTCASS','TGAVTSGYY',    'PNWFQQKPGQAPRALIY','STS',        'NKHSWTP','ARFSGSL','LGGKAALTLSGVQPEDEAEYYC','LLYYGGAQ'],
    'IGLV7-46':[  'QAVVTQEPS','LTVSPGGTVTLTCGSS','TGAVTSGHY',    'PYWFQQKPGQAPRTLIY','DTS',        'NKHSWTP','ARFSGSL','LGGKAALTLSGAQPEDEAEYYC','LLSYSGAR'],
    'IGLV8-61':[  'QTVVTQEPS','FSVSPGGTVTLTCGLS','SGSVSTSYY',    'PSWYQQTPGQAPRTLIY','STN',        'TRSSGVP','DRFSGSI','LGNKAALTITGAQADDESDYYC','VLYMGSGI'],
    'IGLV9-49':[  'QPVLTQPPS','ASASLGASVTLTCTLS','SGYSNYK',      'VDWYQQRPGKGPRFVMR','VGTGGIVG',   'SKGDGIP','DRFSVLG','SGLNRYLTIKNIQEEDESDYHC','GADHGSGSNFV*'],
    'IGLV10-54':[ 'QAGLTQPPS','VSKGLRQTATLTCTGN','SNNVGNQG',     'AAWLQQHQGHPPKLLSY','RNN',        'NRPSGIS','ERLSASR','SGNTASLTITGLQPEDEADYYC','SAWDSSLSA'],
    'IGLV11-55':[ 'RPVLTQPPS','LSASPGATARLPCTLS','SDLSVGGKN',    'MFWYQQKPGSSPRLFLY','HYSDSDK',    'QLGPGVP','SRVSGSKETSSNTAFLLISGLQPEDEADYYC', 'QVYESSAN']},

    'light_chain_lambda_J':{

    'IGLJ1':'YVFGTGTKVTVL',
    'IGLJ2':'VVFGGGTKLTVL',
    'IGLJ3':'VVFGGGTKLTVL',
    'IGLJ4':'FVFGGGTQLIIL',
    'IGLJ5':'WVFGEGTELTVL',
    'IGLJ6':'NVFGSGTKVTVL',
    'IGLJ7':'AVFGGGTQLTVL'}

    }
}


class AntibodyGermLine:

    @staticmethod
    def profile_antibody_db_humanization(fasta_file_path, save_folder):
        #human_antibody_germ_line = AntibodyGermLine()
        fasta_file = FastaFile.read(fasta_file_path)
        antibodies = {}
        antibodies[AntibodyChain.LIGHT] = {}
        antibodies[AntibodyChain.HEAVY] = {}
        for header, string in fasta_file.items():
            if header.find('VL') > -1:
                antibodies[AntibodyChain.LIGHT][header] = ProteinSequence(string)
            elif header.find('VH') > -1:
                antibodies[AntibodyChain.HEAVY][header] = ProteinSequence(string)
            else:
                continue
        stats = {AntibodyChain.LIGHT:{'min':9.9e9, 'max':-9.9e9, 'min_ab':None, 'max_ab':None},
                 AntibodyChain.HEAVY:{'min':9.9e9, 'max':-9.9e9, 'min_ab':None, 'max_ab':None}}
        scores = {AntibodyChain.LIGHT:[], AntibodyChain.HEAVY:[]}
        for ab_name in antibodies[AntibodyChain.LIGHT]:
            #print('Working on ...', ab_name)
            light_chain = antibodies[AntibodyChain.LIGHT][ab_name]
            heavy_chain = antibodies[AntibodyChain.HEAVY][ab_name.replace('VL', 'VH')]
            ab = Antibody(ab_name, light_chain, heavy_chain)
            for chain in [AntibodyChain.LIGHT, AntibodyChain.HEAVY]:
                profile = ab.get_homologous_human_frameworks(chain)
                #print(ab_name, chain, profile)
                score = profile[0][0]
                scores[chain].append(score)
                if score < stats[chain]['min']:
                    stats[chain]['min'] = score
                    stats[chain]['min_ab'] = ab_name
                if score > stats[chain]['max']:
                    stats[chain]['max'] = score
                    stats[chain]['max_ab'] = ab_name
        for chain in scores:
            stats[chain]['mean'] = sum(scores[chain]) / len(scores[chain])
            dev2 = 0.0
            for score in scores[chain]:
                dev2 += (score - stats[chain]['mean'])**2
            stats[chain]['stdev'] = (dev2 / len(scores[chain]))**0.5
        save_file = os.path.join(save_folder, 'antibody_db_humanization.dat')
        with open(save_file, 'wb') as pickle_file:
            pickle.dump(stats, pickle_file)
        return stats

    def __init__(self, organism='Human', germ_line_dictionary=human_ab_germ_line, substitution_matrix=default_subsitution_matrix):
        self.organism = organism
        self.sequences = germ_line_dictionary
        self.germ_line = {}
        self.substitution_matrix = substitution_matrix
        self.generate_germ_line()

    def generate_germ_line(self):
        for chain in self.sequences.keys():
            self.germ_line[chain] = {}
            for locus in add_regions[chain].keys():
                self.germ_line[chain][locus] = {}
                for framework in self.sequences[chain][locus]:
                    sequence = "".join(self.sequences[chain][locus][framework]).replace(" ", "")
                    add_sequences = self.sequences[chain][add_regions[chain][locus]]
                    for add_framework in add_sequences:
                        recomb_sequence = "".join((sequence, add_sequences[add_framework]))
                        recomb_framework = '{}::{}'.format(framework, add_framework)
                        self.germ_line[chain][locus][recomb_framework] = {}
                        self.germ_line[chain][locus][recomb_framework]['sequence'] = ProteinSequence(recomb_sequence)
                        self.germ_line[chain][locus][recomb_framework]['9mers'] = []
                        for n in range(0, len(recomb_sequence) - 8):
                            ninemer = recomb_sequence[n:n + 9]
                            self.germ_line[chain][locus][recomb_framework]['9mers'].append(ProteinSequence(ninemer))
        return

    def get_sequence(self, chain, framework):
        for locus in self.germ_line[chain]:
            if framework in self.germ_line[chain][locus]:
                return ProteinSequence(self.germ_line[chain][locus][framework]['sequence'])
        return

    def scan_human_frameworks(self, protein_sequence, chain):
        result = []
        for locus in self.germ_line[chain]:
            for framework in self.germ_line[chain][locus]:
                alignment = bioalign.align_optimal(protein_sequence, self.germ_line[chain][locus][framework]['sequence'], self.substitution_matrix, max_number=1)
                result.append((alignment[0].score, locus, framework, alignment[0].get_gapped_sequences()[1]))
        return sorted(result, reverse=True)






if __name__ == "__main__":
    from biotite.sequence.io import fasta
    from biotite.sequence import ProteinSequence
    from amber_biotools.antibody import Antibody
    fapath = '/Users/gordon/Google Drive/amber/Python/amber_biotools/test_data/sequences/adalimumab_FASTA.txt'
    seq_data = fasta.FastaFile.read(fapath)
    chains = []
    for header, string in seq_data.items():
        chains.append(string)
    light_chain = ProteinSequence(chains[0])
    print(light_chain)
    heavy_chain = ProteinSequence(chains[1])
    ab = Antibody('My antibody', light_chain, heavy_chain)
    print(ab.light_sequence)
    gl = AntibodyGermLine('human', human_ab_germ_line, bioalign.SubstitutionMatrix.std_protein_matrix())
    #scan = gl.scan_human_frameworks(ab.get_variable_region(AntibodyChain.LIGHT)[2], AntibodyChain.LIGHT)
    scan = gl.scan_human_frameworks(ab.get_variable_region(AntibodyChain.HEAVY)[2], AntibodyChain.HEAVY)
    print(scan)
    for result in scan[:20]:
        print(chains[1][:121])
        print(result[3], result[2], result[0])
        print()
    print()
    print(gl.get_sequence(AntibodyChain.HEAVY, 'IGHV1-46::IGHJ6'))
    approved_abs = '/Users/gordon/Google Drive/amber/Python/amber_biotools/test_data/sequences/approved_ab_sequences.txt'
    sandbox = '/Users/gordon/Google Drive/amber/Python/amber_biotools/sandbox'
    abs = AntibodyGermLine.profile_antibody_db_humanization(approved_abs, save_folder=sandbox)
    print(abs)
